// LOCALHOST 
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/632a2f1616dc784731c9c7e1
### 
GET http://localhost:3000/contacts/632a2f1616dc784731c9c7e2
### 
GET http://localhost:3000/contacts/632a2f1616dc784731c9c7e3 



// PRODUCTION Deploy 
### 
GET https://cse341-node-wk0g.onrender.com/contacts
### 
GET https://cse341-node-wk0g.onrender.com/contacts/632a2f1616dc784731c9c7e1
### 
GET https://cse341-node-wk0g.onrender.com/contacts/632a2f1616dc784731c9c7e2
### 
GET https://cse341-node-wk0g.onrender.com/contacts/632a2f1616dc784731c9c7e3 


//test

# POST http://localhost:3000/contacts
# POST http://localhost:3000/contacts?contact=id&number=554488
# content-type: application/json
# {
#     "name": "Ibrahimovic"
# }


