// LOCALHOST 
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/632ed41c15bda6a4570f6fcb
### 
GET http://localhost:3000/contacts/632a2f1616dc784731c9c7e2
### 
GET http://localhost:3000/contacts/632a2f1616dc784731c9c7e3 
### 
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

    {
        "firstName": "Pato",
        "lastName": "O'Ward",
        "email": "Poward@gmail.com",
        "favoriteColor": "Orange",
        "birthday": "02/20/1996"
    }
### 
PUT  http://localhost:3000/contacts/632bceb4e23bdb447eb452a0
content-type: application/json

    {
        "firstName": "Checo",
        "lastName": "Perez",
        "email": "sp@gmail.com",
        "favoriteColor": "Red",
        "birthday": "14/04/1975"
    }
### 
DELETE http://localhost:3000/contacts/632bceb4e23bdb447eb452a0


// PRODUCTION Deploy 
### 
GET https://cse341-node-wk0g.onrender.com/contacts
### 
GET https://cse341-node-wk0g.onrender.com/contacts/632ed41c15bda6a4570f6fcb
### 
GET https://cse341-node-wk0g.onrender.com/contacts/632a2f1616dc784731c9c7e2
### 
GET https://cse341-node-wk0g.onrender.com/contacts/632a2f1616dc784731c9c7e3 
### 
POST http://cse341-node-wk0g.onrender.com/contacts HTTP/1.1
content-type: application/json

    {
        "firstName": "Valeria",
        "lastName": "Olvera",
        "email": "Vale@gmail.com",
        "favoriteColor": "Beige",
        "birthday": "02/30/2005"
    }
### 
PUT  http://cse341-node-wk0g.onrender.com/contacts/632bd6981a5da57930a60dc1
content-type: application/json

    {
        "firstName": "Checo",
        "lastName": "Perez",
        "email": "sp@gmail.com",
        "favoriteColor": "Red",
        "birthday": "14/04/1975"
    }
### 
DELETE http://cse341-node-wk0g.onrender.com/contacts/632bd6981a5da57930a60dc1


